name: NewClasses
main: ru.newplugin.newclasses.NewClasses
version: ${project.version}
authors: [BlusterySasha, Mykea, l_MrBoom_l]
description: Плагин на классы.
api-version: 1.17
#
# © NewPlugin
#
commands:
  sc:
    aliases: [setclass]
    permission: "newplugin.setclass"